background       = "#1C1C1E"
background-alpha = 0.86
text             = "#F5F5F7"
border           = "hyprland.active-border"
border-alpha     = 0.46
border-width     = 1
countdown        = "#0A84FF"
